// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW1BG9HKxNglUE6wvvIf5OM4FbfNC3cME',
    appId: '1:403956670231:web:7701bf98053ffd0feb2152',
    databaseURL: "https://qmsys-77522-default-rtdb.firebaseio.com",
    messagingSenderId: '403956670231',
    projectId: 'qmsys-77522',
    authDomain: 'qmsys-77522.firebaseapp.com',
    storageBucket: 'qmsys-77522.appspot.com',
    measurementId: 'G-V8FK5FEW6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP2YsqeCJbzEzCxLcd846KSlMJIycdnF4',
    appId: '1:403956670231:android:30ccd83e50bb339ceb2152',
    databaseURL: "https://qmsys-77522-default-rtdb.firebaseio.com",
    messagingSenderId: '403956670231',
    projectId: 'qmsys-77522',
    storageBucket: 'qmsys-77522.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPPCa3HRZzT64sOtWcNdOEVUbll9knHRA',
    appId: '1:403956670231:ios:b07888407bf536efeb2152',
    messagingSenderId: '403956670231',
    projectId: 'qmsys-77522',
    storageBucket: 'qmsys-77522.appspot.com',
    iosBundleId: 'com.example.qms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPPCa3HRZzT64sOtWcNdOEVUbll9knHRA',
    appId: '1:403956670231:ios:b07888407bf536efeb2152',
    messagingSenderId: '403956670231',
    projectId: 'qmsys-77522',
    storageBucket: 'qmsys-77522.appspot.com',
    iosBundleId: 'com.example.qms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW1BG9HKxNglUE6wvvIf5OM4FbfNC3cME',
    appId: '1:403956670231:web:2d5d08e3ce183a7ceb2152',
    messagingSenderId: '403956670231',
    projectId: 'qmsys-77522',
    authDomain: 'qmsys-77522.firebaseapp.com',
    storageBucket: 'qmsys-77522.appspot.com',
    measurementId: 'G-1BW5T1ZXHR',
  );
}
